version: '3'

services:
  playground-storage:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - "MINIO_ROOT_USER=Q3AM3UQ867SPQQA43P2F"
      - "MINIO_ROOT_PASSWORD=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
    entrypoint: sh
    command: >
      -c 'mkdir -p /export/adventureworks && minio server /export --console-address :9001'
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 2

  playground-db:
    volumes:
      - "/var/lib/postgresql/data"
    image: postgres:16
    ports:
      - "54316:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: [ "CMD", "psql", "-U", "postgres" ]
      interval: 5s
      timeout: 1s
      retries: 3

  playground-dbs-filler:
    environment:
      PGPASSWORD: "example"
      TMP_DIR: "/tmp/schema"
      ORIGINAL_DB_NAME: "original"
      TRANSFORMED_DB_NAME: "transformed"
      DBHOST: "db"
      DBUSER: "postgres"
      DBPASSWORD: "example"
    build:
      context: docker/playground/filldb
    depends_on:
      playground-db:
        condition: service_healthy

  greenmask:
    volumes:
      - ./playground:/var/lib/playground
    image: "greenmask/greenmask:latest"
    working_dir: /var/lib/playground
    depends_on:
      playground-dbs-filler:
        condition: service_completed_successfully
      playground-storage:
        condition: service_healthy
    entrypoint: "/var/lib/playground/run.sh"

  greenmask-from-source:
    working_dir: /var/lib/playground
    volumes:
      - ./playground:/var/lib/playground
    build:
      dockerfile: docker/greenmask/Dockerfile
      context: ./
    depends_on:
      playground-dbs-filler:
        condition: service_completed_successfully
      playground-storage:
        condition: service_healthy
    entrypoint: "/var/lib/playground/run.sh"
