site_name: Greenmask — PostgreSQL masking and obfuscation tool

# Theme
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.indexes
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    # - navigation.sections
    - navigation.tabs
    #    - navigation.top
    #    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  #    - toc.follow
  palette:
    scheme: default
    primary: teal
    accent: indigo
    toggle:
      icon: material/brightness-7


# Markdown extensions
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - tables

nav:
  - Home:
      - Home: index.md
  - Documentation:
      - Installation: installation.md
      - Configuration: configuration.md
      - Architecture: architecture.md
      - Playground: playground.md
      - Commands: commands.md
      - Transformers:
          - built_in_transformers/index.md
          - Standard transformers:
              - built_in_transformers/standard_transformers/index.md
              - Cmd: built_in_transformers/standard_transformers/cmd.md
              - Dict: built_in_transformers/standard_transformers/dict.md
              - Hash: built_in_transformers/standard_transformers/hash.md
              - Masking: built_in_transformers/standard_transformers/masking.md
              - NoiseDate: built_in_transformers/standard_transformers/noise_date.md
              - NoiseFloat: built_in_transformers/standard_transformers/noise_float.md
              - NoiseInt: built_in_transformers/standard_transformers/noise_int.md
              - RandomBool: built_in_transformers/standard_transformers/random_bool.md
              - RandomChoice: built_in_transformers/standard_transformers/random_choice.md
              - RandomDate: built_in_transformers/standard_transformers/random_date.md
              - RandomFloat: built_in_transformers/standard_transformers/random_float.md
              - RandomInt: built_in_transformers/standard_transformers/random_int.md
              - RandomString: built_in_transformers/standard_transformers/random_string.md
              - RandomUuid: built_in_transformers/standard_transformers/random_uuid.md
              - RandomLatitude: built_in_transformers/standard_transformers/random_latitude.md
              - RandomLongitude: built_in_transformers/standard_transformers/random_longitude.md
              - RandomUnixTime: built_in_transformers/standard_transformers/random_unix_time.md
              - RandomDayOfWeek: built_in_transformers/standard_transformers/random_day_of_week.md
              - RandomDayOfMonth: built_in_transformers/standard_transformers/random_day_of_month.md
              - RandomMonthName: built_in_transformers/standard_transformers/random_month_name.md
              - RandomYearString: built_in_transformers/standard_transformers/random_year_string.md
              - RandomCentury: built_in_transformers/standard_transformers/random_century.md
              - RandomTimezone: built_in_transformers/standard_transformers/random_timezone.md
              - RandomEmail: built_in_transformers/standard_transformers/random_email.md
              - RandomUsername: built_in_transformers/standard_transformers/random_username.md
              - RandomPassword: built_in_transformers/standard_transformers/random_password.md
              - RandomMacAddress: built_in_transformers/standard_transformers/random_mac_address.md
              - RandomDomainName: built_in_transformers/standard_transformers/random_domain_name.md
              - RandomURL: built_in_transformers/standard_transformers/random_url.md
              - RandomIPv4: built_in_transformers/standard_transformers/random_ipv4.md
              - RandomIPv6: built_in_transformers/standard_transformers/random_ipv6.md
              - RandomWord: built_in_transformers/standard_transformers/random_word.md
              - RandomSentence: built_in_transformers/standard_transformers/random_sentence.md
              - RandomParagraph: built_in_transformers/standard_transformers/random_paragraph.md
              - RandomCCType: built_in_transformers/standard_transformers/random_cc_type.md
              - RandomCCNumber: built_in_transformers/standard_transformers/random_cc_number.md
              - RandomCurrency: built_in_transformers/standard_transformers/random_currency.md
              - RandomAmountWithCurrency: built_in_transformers/standard_transformers/random_amount_with_currency.md
              - RandomName: built_in_transformers/standard_transformers/random_name.md
              - RandomLastName: built_in_transformers/standard_transformers/random_last_name.md
              - RandomFirstName: built_in_transformers/standard_transformers/random_first_name.md
              - RandomFirstNameMale: built_in_transformers/standard_transformers/random_first_name_male.md
              - RandomFirstNameFemale: built_in_transformers/standard_transformers/random_first_name_female.md
              - RandomTitleMale: built_in_transformers/standard_transformers/random_title_male.md
              - RandomTitleFemale: built_in_transformers/standard_transformers/random_title_female.md
              - RandomPhoneNumber: built_in_transformers/standard_transformers/random_phone_number.md
              - RandomTollFreePhoneNumber: built_in_transformers/standard_transformers/random_toll_free_phone_number.md
              - RandomE164PhoneNumber: built_in_transformers/standard_transformers/random_e164_phone_number.md
              - RealAddress: built_in_transformers/standard_transformers/real_address.md
              - RegexpReplace: built_in_transformers/standard_transformers/regexp_replace.md
              - Replace: built_in_transformers/standard_transformers/replace.md
              - SetNull: built_in_transformers/standard_transformers/set_null.md
          - Advanced transformers:
              - built_in_transformers/advanced_transformers/index.md
              - Json: built_in_transformers/advanced_transformers/json.md
              - Template: built_in_transformers/advanced_transformers/template.md
              - TemplateRecord: built_in_transformers/advanced_transformers/template_record.md
              - Custom functions:
                - built_in_transformers/advanced_transformers/custom_functions/index.md
                - Core custom functions: built_in_transformers/advanced_transformers/custom_functions/core_functions.md
                - Faker function: built_in_transformers/advanced_transformers/custom_functions/faker_function.md
  - Release notes:
      - Greenmask 0.1.5: release_notes/greenmask_0_1_5.md
      - Greenmask 0.1.4: release_notes/greenmask_0_1_4.md
      - Greenmask 0.1.3: release_notes/greenmask_0_1_3.md
      - Greenmask 0.1.2: release_notes/greenmask_0_1_2.md
      - Greenmask 0.1.1: release_notes/greenmask_0_1_1.md
      - Greenmask 0.1.0: release_notes/greenmask_0_1_0.md
      - Greenmask 0.1.0 Beta: release_notes/greenmask_0_1_0_beta.md

repo_url: https://github.com/GreenmaskIO/greenmask
repo_name: GreenmaskIO/greenmask
site_url: https://greenmask.io
copyright: Copyright &copy; 2024 Greenmask


extra:
  #    version:
  #    provider: mike
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/GreenmaskIO
    - icon: fontawesome/brands/discord
      link: https://discord.gg/97AKHdGD
    - icon: fontawesome/brands/github
      link: https://github.com/GreenmaskIO/greenmask

plugins:
  - social
  - search
