name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'LICENSE'
      - 'getting_started.md'

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build:
    uses: ./.github/workflows/build.yml
    needs: 
      - tests

  docs:
    uses: ./.github/workflows/docs.yml
    if: startsWith(github.ref, 'refs/tags/v')
    needs: 
      - build
      